name: Deploy Connect to Powerhouse Production

on:
  push:
    branches: [main]

env:
  HUSKY: 0

jobs:
  build:
    environment: Powerhouse Production
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up heroku
        run: sudo curl https://cli-assets.heroku.com/install.sh | sh
      - name: Build, Push and Release APP to Heroku. # Your custom step name
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          docker_options: >-
            --build-arg BASE_PATH=/powerhouse/connect
            --build-arg PH_CONNECT_BASE_HREF=/powerhouse/connect/
            --build-arg PH_CONNECT_ROUTER_BASENAME=/powerhouse/connect
            --build-arg PH_CONNECT_SENTRY_DSN=${{ secrets.SENTRY_DSN }}
            --build-arg PH_CONNECT_SENTRY_ENV=${{ secrets.SENTRY_ENV }}
            --build-arg PH_CONNECT_DEFAULT_DRIVES_URL=https://apps.powerhouse.io/powerhouse/switchboard/d/powerhouse
            --build-arg PH_CONNECT_SEARCH_BAR_ENABLED=false
          process_type: web