name: Deploy Connect to MakerDAO Production

on:
  push:
    branches: [deployments/makerdao]

env:
  HUSKY: 0

jobs:
  build:
    environment: MakerDAO Production
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up heroku
        run: sudo curl https://cli-assets.heroku.com/install.sh | sh
      - name: Build, Push and Release APP to Heroku. # Your custom step name
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          docker_options: >-
            --build-arg BASE_PATH=/makerdao/connect
            --build-arg PH_CONNECT_BASE_HREF=/makerdao/connect/
            --build-arg PH_CONNECT_ROUTER_BASENAME=/makerdao/connect
            --build-arg PH_CONNECT_SENTRY_DSN=${{ secrets.SENTRY_DSN }}
            --build-arg PH_CONNECT_SENTRY_ENV=${{ secrets.SENTRY_ENV }}
            --build-arg PH_CONNECT_SEARCH_BAR_ENABLED=false
            --build-arg PH_CONNECT_DEFAULT_DRIVES_URL=https://apps.powerhouse.io/makerdao/switchboard/d/b443d823-3e4d-4e60-ae44-45edafd5f632
            --build-arg PH_CONNECT_RWA_ALLOW_LIST=${{secrets.PH_CONNECT_RWA_ALLOW_LIST}}
          process_type: web