name: Deploy Connect to Arbitrum Production

on:
  push:
    branches: [deployments/arbitrum]

env:
  HUSKY: 0

jobs:
  build:
    environment: Arbitrum Production
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up heroku
        run: sudo curl https://cli-assets.heroku.com/install.sh | sh
      - name: Build, Push and Release APP to Heroku. # Your custom step name
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          docker_options: >-
            --build-arg BASE_PATH=/arbitrum/connect
            --build-arg PH_CONNECT_BASE_HREF=/arbitrum/connect/
            --build-arg PH_CONNECT_ROUTER_BASENAME=/arbitrum/connect
            --build-arg PH_CONNECT_SENTRY_DSN=${{ secrets.SENTRY_DSN }}
            --build-arg PH_CONNECT_SENTRY_ENV=${{ secrets.SENTRY_ENV }}
            --build-arg PH_CONNECT_ENABLED_EDITORS=ARBLTIPGrantee
            --build-arg PH_CONNECT_DISABLE_ADD_PUBLIC_DRIVES=true
            --build-arg PH_CONNECT_DISABLE_ADD_CLOUD_DRIVES=true
            --build-arg PH_CONNECT_DISABLE_ADD_LOCAL_DRIVES=true
            --build-arg PH_CONNECT_DISABLE_DELETE_PUBLIC_DRIVES=true
            --build-arg PH_CONNECT_DISABLE_DELETE_CLOUD_DRIVES=true
            --build-arg PH_CONNECT_DISABLE_DELETE_LOCAL_DRIVES=true
            --build-arg PH_CONNECT_LOCAL_DRIVES_ENABLED=false
            --build-arg PH_CONNECT_SEARCH_BAR_ENABLED=false
            --build-arg PH_CONNECT_DEFAULT_DRIVES_URL=https://apps.powerhouse.io/arbitrum/switchboard/d/arbitrum
            --build-arg PH_CONNECT_RENOWN_CHAIN_ID=42161
            --build-arg PH_CONNECT_HIDE_DOCUMENT_MODEL_SELECTION_SETTINGS=true
          process_type: web